# Generated by Django 3.0.7 on 2020-06-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=200)),
                ('sub_file', models.CharField(max_length=200)),
                ('sub_year', models.CharField(max_length=20)),
                ('sub_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=200)),
                ('year_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='department_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
