# Generated by Django 3.0.7 on 2020-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200609_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=300)),
                ('department_name', models.CharField(max_length=200)),
                ('college_slug', models.CharField(default=1, max_length=200)),
            ],
        ),
    ]
