# Generated by Django 3.0.7 on 2020-06-15 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_department_college_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=20)),
                ('sem_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Semester',
            },
        ),
        migrations.DeleteModel(
            name='year',
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name_plural': 'Colleges'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.RemoveField(
            model_name='college',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub_year',
        ),
        migrations.AddField(
            model_name='subject',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='college_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.College', verbose_name='College'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Semester', verbose_name='Semester'),
        ),
    ]
