# Generated by Django 3.0.7 on 2020-06-19 11:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200619_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_published', models.DateTimeField(default=datetime.datetime(2020, 6, 19, 17, 25, 1, 735119), verbose_name='date published')),
                ('file_pdf', models.FileField(upload_to='')),
                ('sem_slug', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='college_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.College', verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 17, 25, 1, 734121), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Department', verbose_name='Department'),
        ),
    ]
